spring.application.name=wego

spring.config.import=classpath:application-local-secret.properties

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# tour api
tourapi.baseurl=https://apis.data.go.kr/B551011/KorService2
tourapi.location=/areaCode2
tourapi.touristSpot=/areaBasedList2

#ai

spring.ai.vertex.gemini.chat.options.model=gemini-2.0-flash